guess_list = ['able', 'act', 'against', 'animal', 'answer', 'beauty', 'because', 'beginning', 'between', 'blue', 'boy',
              'call', 'center', 'common', 'computer', 'country', 'crt', 'cry', 'dark', 'decide', 'develop', 'down',
              'dry', 'each', 'empty', 'even', 'fact', 'figure', 'first', 'follow', 'force', 'full', 'game',
              'government', 'hand', 'hard', 'head', 'here', 'holiday', 'home', 'hot', 'i', 'if', 'in', 'it',
              'just', 'keep', 'kind', 'king', 'land', 'large', 'last', 'laugh', 'learn', 'long', 'love', 'machine',
              'make', 'map', 'men', 'money', 'moon', 'move', 'my', 'near', 'need', 'new', 'number', 'object', 'of',
              'off', 'or', 'our', 'out', 'page', 'pattern', 'picture', 'possible', 'press', 'produce', 'pull', 'put',
              'queen', 'quick', 'random', 'read', 'real', 'record', 'rest', 'right', 'said', 'saw', 'say', 'science',
              'second', 'self', 'sentence', 'she', 'should', 'side', 'sleep', 'special', 'star', 'stay', 'sun',
              'surface', 'table', 'tail', 'than', 'that', 'them', 'then', 'they', 'thousand', 'time', 'to', 'too',
              'town', 'tree', 'try', 'two', 'under', 'up', 'us', 'use', 'very', 'voice', 'wait', 'was', 'were', 'what',
              'when', 'where', 'while', 'whp', 'why', 'will', 'with', 'women', 'world', 'year', 'yellow', 'yet', 'you',
              'abukir', 'angkor', 'banker', 'berake', 'bicker', 'booker', 'bunker', 'cracks', 'cranks', 'darked',
              'decker', 'drunks', 'evoker''abukir', 'angkor', 'banker', 'berake', 'bicker', 'booker', 'bunker',
              'cracks', 'cranks','darked', 'decker', 'drunks', 'evoker', 'arawak', 'decapitator', 'executioner',
              'executor', 'headsman', 'assassin', 'cutthroat', 'homicide', 'killer', 'manslayer', 'murderer', 'butcher',
              'massacrer', 'slaughterer', 'slayer', 'murderess']